trigger:
  paths:
    include:
      - insta-munch-backend/*

resources:
- repo: self

variables:
  # Use secure variable groups or pipeline variables to store these values
  dockerRegistryServiceConnection: '$(DOCKER_REGISTRY_SERVICE_CONNECTION)'
  imageRepository: '$(IMAGE_REPOSITORY)'
  containerRegistry: '$(CONTAINER_REGISTRY)'
  dockerfilePath: '$(Build.SourcesDirectory)/insta-munch-backend/DockerFile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build Docker Image
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        dockerfile: $(dockerfilePath)
        tags: '$(tag)'

- stage: Push
  displayName: Push Docker Image
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Push
    displayName: Push Docker Image
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: Push Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

- stage: Update
  displayName: Update Kubernetes Manifests
  dependsOn: Push
  condition: succeeded()
  jobs:
  - job: Update
    displayName: Update Kubernetes Manifests
    pool:
      name: Default
    steps:
    - task: ShellScript@2
      displayName: Run Update Script
      inputs:
        scriptPath: 'Scripts/update.sh'
        args: 'backend $(containerRegistry) $(imageRepository) $(tag)'
