apiVersion: v1
kind: Service
metadata:
  labels:
    app: insta-frontend
  name: insta-frontend
spec:
  type: NodePort
  ports:
  - name: "insta-frontend-service"
    port: 3000     
    targetPort: 3000 
    nodePort: 31000  
  selector:
    app: insta-frontend

  